import type { Doctor } from "../interface/DoctorInterface";

export const doctorsData:Doctor[] = [
  {
    id: "DOC002",
    name: "Dr. Sarah Khan",
    specialization: "Dermatologist",
    qualification: ["MBBS - Aga Khan University", "FCPS Dermatology"],
    experience: 9,
    hospital: "Aga Khan Hospital",
    location: "Karachi, Pakistan",
    consultationFee: 2000,
    rating: 4.7,
    totalReviews: 210,
    about:
      "Specialist in skin diseases, acne treatment, cosmetic dermatology, and laser therapy.",
    languages: ["English", "Urdu"],
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    availableSlots: ["9:00 AM - 12:00 PM", "2:00 PM - 5:00 PM"],
    image: "/doctors/sarah.jpg",
    status: "Available",
},

{
    id: "DOC003",
    name: "Dr. Bilal Ahmed",
    specialization: "Neurologist",
    qualification: ["MBBS - Karachi University", "FCPS Neurology"],
    experience: 14,
    hospital: "Liaquat National Hospital",
    location: "Karachi, Pakistan",
    consultationFee: 3000,
    rating: 4.9,
    totalReviews: 412,
    about:
    "Expert in neurological disorders including epilepsy, stroke, migraines, and nerve diseases.",
    languages: ["English", "Urdu"],
    availableDays: ["Monday", "Thursday"],
    availableSlots: ["11:00 AM - 2:00 PM", "4:00 PM - 7:00 PM"],
    image: "/doctors/bilal.jpg",
    status: "Available",
},

{
    id: "DOC004",
    name: "Dr. Fatima Noor",
    specialization: "Pediatrician",
    qualification: ["MBBS - Dow University", "DCH Pediatrics"],
    experience: 8,
    hospital: "South City Hospital",
    location: "Karachi, Pakistan",
    consultationFee: 1800,
    rating: 4.6,
    totalReviews: 195,
    about:
    "Dedicated pediatrician focusing on child health, vaccination, and developmental care.",
    languages: ["English", "Urdu"],
    availableDays: ["Monday", "Tuesday", "Friday"],
    availableSlots: ["10:00 AM - 1:00 PM", "3:00 PM - 6:00 PM"],
    image: "/doctors/fatima.jpg",
    status: "Available",
},

{
    id: "DOC005",
    name: "Dr. Hassan Ali",
    specialization: "Orthopedic Surgeon",
    qualification: ["MBBS - Ziauddin University", "MS Orthopedics"],
    experience: 15,
    hospital: "Ziauddin Hospital",
    location: "Karachi, Pakistan",
    consultationFee: 2800,
    rating: 4.8,
    totalReviews: 276,
    about:
    "Orthopedic surgeon specializing in bone fractures, joint replacements, and sports injuries.",
    languages: ["English", "Urdu"],
    availableDays: ["Wednesday", "Friday", "Saturday"],
    availableSlots: ["9:30 AM - 12:30 PM", "5:00 PM - 8:00 PM"],
    image: "/doctors/hassan.jpg",
    status: "Available",
},

{
    id: "DOC006",
    name: "Dr. Ayesha Siddiqui",
    specialization: "Gynecologist",
    qualification: ["MBBS - Aga Khan University", "FCPS Gynecology"],
    experience: 11,
    hospital: "Aga Khan Hospital",
    location: "Karachi, Pakistan",
    consultationFee: 2500,
    rating: 4.7,
    totalReviews: 305,
    about:
    "Experienced gynecologist providing care for pregnancy, infertility, and women's health issues.",
    languages: ["English", "Urdu"],
    availableDays: ["Monday", "Wednesday", "Saturday"],
    availableSlots: ["10:00 AM - 1:00 PM", "4:00 PM - 7:00 PM"],
    image: "/doctors/ayesha.jpg",
    status: "Not Available",
},

{
    id: "DOC007",
    name: "Dr. Imran Shah",
    specialization: "ENT Specialist",
    qualification: ["MBBS - Dow University", "FCPS ENT"],
    experience: 10,
    hospital: "Civil Hospital Karachi",
    location: "Karachi, Pakistan",
    consultationFee: 2200,
    rating: 4.5,
    totalReviews: 168,
    about:
    "Specialist in ear, nose, and throat diseases including sinus issues and hearing disorders.",
    languages: ["English", "Urdu"],
    availableDays: ["Tuesday", "Thursday"],
    availableSlots: ["11:00 AM - 2:00 PM", "6:00 PM - 9:00 PM"],
    image: "/doctors/imran.jpg",
    status: "Available",
},

{
    id: "DOC008",
    name: "Dr. Sana Malik",
    specialization: "Psychiatrist",
    qualification: ["MBBS - Karachi Medical College", "FCPS Psychiatry"],
    experience: 7,
    hospital: "Jinnah Postgraduate Medical Center",
    location: "Karachi, Pakistan",
    consultationFee: 2300,
    rating: 4.6,
    totalReviews: 142,
    about:
    "Mental health specialist treating anxiety, depression, and stress-related disorders.",
    languages: ["English", "Urdu"],
    availableDays: ["Wednesday", "Friday"],
    availableSlots: ["12:00 PM - 3:00 PM", "5:00 PM - 8:00 PM"],
    image: "/doctors/sana.jpg",
    status: "Available",
},
];
